import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import plugin, { LIBRARY_TYPE, ITEM_TYPE, KINDS, STATUSES, clampRating, stars, filterItems, defaultLibraryForPicker, migrateLooseItems, normalizeIsbn, mergeEmptyFields, searchOpenLibrary, loadOpenLibraryChoice } from "./main.js";
assert.equal(plugin.manifest.version,"0.3.0");
assert.equal(plugin.manifest.apiVersion,"1.28");
assert.equal(LIBRARY_TYPE,"notible.library.library");
assert.equal(ITEM_TYPE,"notible.library.item");
assert.deepEqual(KINDS,["book","film","series","game","other"]);
assert.deepEqual(STATUSES,["wishlist","in-progress","done","dropped"]);
assert.equal(clampRating(9),5); assert.equal(clampRating(-1),0); assert.equal(clampRating(undefined),0); assert.equal(stars(0),"☆☆☆☆☆"); assert.equal(stars(4),"★★★★☆");
const item=(title,props,updated_at)=>({title,props:JSON.stringify(props),updated_at});
const rows=[item("A",{kind:"book",status:"done",rating:5,tags:["classic"]},1),item("B",{kind:"game",status:"wishlist",rating:2,tags:[]},2)];
assert.deepEqual(filterItems(rows,{kind:"book",status:"",tag:"",sort:"date"}).map(x=>x.title),["A"]);
assert.deepEqual(filterItems(rows,{kind:"",status:"",tag:"",sort:"rating"}).map(x=>x.title),["A","B"]);
assert.equal(defaultLibraryForPicker([{id:"books"},{id:"films"}],"films"),"films");
assert.equal(defaultLibraryForPicker([{id:"books"},{id:"films"}],"folder"),"books");
assert.equal(normalizeIsbn("978-0-441-17271-9"),"9780441172719"); assert.equal(normalizeIsbn("0-306-40615-2"),"0306406152"); assert.equal(normalizeIsbn("Dune"),"");
assert.deepEqual(mergeEmptyFields({title:"Typed title",creator:"",year:"",description:"Mine"},{title:"Dune",creator:"Frank Herbert",year:1965,description:"Remote",cover:"media/x.jpg"}),{title:"Typed title",creator:"Frank Herbert",year:1965,description:"Mine",cover:"media/x.jpg"});
const fixtureFetch=async(url)=>({ok:true,json:async()=>url.includes("search.json")?{docs:[{key:"/works/OL893415W",title:"Dune",author_name:["Frank Herbert"],first_publish_year:1965,isbn:["9780441172719"],cover_i:9269962}]}:{}});
assert.deepEqual(await searchOpenLibrary("Dune",fixtureFetch),[{title:"Dune",creator:"Frank Herbert",year:1965,isbn:"9780441172719",coverId:9269962,workKey:"/works/OL893415W",link:"https://openlibrary.org/works/OL893415W",description:""}]);

// Review #46: an unknown ISBN is "no books"; only what the form lacks is fetched or downloaded.
assert.deepEqual(await searchOpenLibrary("978-0-000-00000-2",async()=>({ok:false,status:404,json:async()=>({})})),[]);
await assert.rejects(()=>searchOpenLibrary("Dune",async()=>({ok:false,status:503,json:async()=>({})})),/HTTP 503/);
let imports=0,fetches=0; const fakeContext={data:{media:{importImageFromUrl:async()=>{imports+=1;return "media/00000000-0000-4000-8000-000000000000.jpg";}}}};
const countingFetch=async()=>{fetches+=1;return {ok:true,json:async()=>({description:"Remote"})};};
const dune={title:"Dune",creator:"Frank Herbert",year:1965,isbn:"9780441172719",coverId:9269962,workKey:"/works/OL893415W",link:"https://openlibrary.org/works/OL893415W",description:""};
const kept=await loadOpenLibraryChoice(fakeContext,dune,countingFetch,{cover:"media/mine.png",description:"Mine"});
assert.deepEqual([imports,fetches,kept.cover,kept.description],[0,0,"",""],"a cover or description the user already has is not downloaded");
const fresh=await loadOpenLibraryChoice(fakeContext,dune,countingFetch,{});
assert.deepEqual([imports,fetches,fresh.description],[1,1,"Remote"],"an empty form gets the work description and the chosen cover only");
const objects=[{id:"legacy",type:ITEM_TYPE,title:"Legacy",parent_id:null,props:"{}"}]; let creates=0; let moves=0;
const migrationContext={i18n:{t:(key)=>key},data:{objects:{query:async({type})=>objects.filter((object)=>object.type===type),create:async(input)=>{creates++;const object={id:"default",parent_id:null,...input};objects.push(object);return object;},move:async(id,parentId)=>{moves++;const object=objects.find((candidate)=>candidate.id===id);object.parent_id=parentId;return object;}}}};
assert.deepEqual(await migrateLooseItems(migrationContext),{moved:1,library:objects[1]});
assert.equal((await migrateLooseItems(migrationContext)).moved,0); assert.equal(creates,1); assert.equal(moves,1);
const source=readFileSync(new URL("./main.js",import.meta.url),"utf8");
const locale=JSON.parse(readFileSync(new URL("./locales/pl.json",import.meta.url),"utf8"));
assert.equal(locale.strings.Sort,"Sortowanie");
for(const banned of ["innerHTML","outerHTML","insertAdjacentHTML","document.write"]) assert.ok(!source.includes(banned));
assert.ok(source.includes("context.data.media.pickImage()"));
assert.ok(source.includes("context.data.media.importImageFromUrl"));
assert.ok(source.includes('t("Find online")'));
assert.ok(source.includes("context.ui.mountSelect")); assert.ok(source.includes("context.ui.mountDatePicker"));
assert.ok(source.includes('behaviour:{container:true}')); assert.ok(source.includes('behaviour:{treeHidden:true}'));
assert.ok(source.includes("defaultLibraryForPicker(libraries, parentId)"));
assert.ok(source.includes("creates:{objectType:ITEM_TYPE")); assert.ok(source.includes("creates:{objectType:LIBRARY_TYPE"));
assert.ok(source.includes('registerObjectTab({id:"library"'));
assert.ok(source.includes('registerObjectTab({id:"item-details"'));
assert.ok(source.includes('registerSlot("editor.toolbar"'));
assert.ok(source.includes('context.ui.openView("libraries")'));
assert.ok(!source.includes('document.createElement("select")')); assert.ok(!source.includes('type = "date"'));
assert.ok(source.includes("renderGeneration"));
assert.ok(source.includes("Promise.all(coverLoads)"));
assert.ok(source.includes('t("Sort")'));
console.log("Notible Library self-check passed.");
