import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ITEM_TYPE, KINDS, STATUSES, clampRating, stars, filterItems } from "./main.js";
assert.equal(ITEM_TYPE,"notible.library.item");
assert.deepEqual(KINDS,["book","film","series","game","other"]);
assert.deepEqual(STATUSES,["wishlist","in-progress","done","dropped"]);
assert.equal(clampRating(9),5); assert.equal(clampRating(-1),0); assert.equal(clampRating(undefined),0); assert.equal(stars(0),"☆☆☆☆☆"); assert.equal(stars(4),"★★★★☆");
const item=(title,props,updated_at)=>({title,props:JSON.stringify(props),updated_at});
const rows=[item("A",{kind:"book",status:"done",rating:5,tags:["classic"]},1),item("B",{kind:"game",status:"wishlist",rating:2,tags:[]},2)];
assert.deepEqual(filterItems(rows,{kind:"book",status:"",tag:"",sort:"date"}).map(x=>x.title),["A"]);
assert.deepEqual(filterItems(rows,{kind:"",status:"",tag:"",sort:"rating"}).map(x=>x.title),["A","B"]);
const source=readFileSync(new URL("./main.js",import.meta.url),"utf8");
const locale=JSON.parse(readFileSync(new URL("./locales/pl.json",import.meta.url),"utf8"));
assert.equal(locale.strings.Sort,"Sortowanie");
for(const banned of ["innerHTML","outerHTML","insertAdjacentHTML","document.write"]) assert.ok(!source.includes(banned));
assert.ok(source.includes("context.data.media.pickImage()"));
assert.ok(source.includes("context.ui.mountSelect"));
assert.ok(source.includes("creates:{objectType:ITEM_TYPE"));
assert.ok(source.includes("renderGeneration"));
assert.ok(source.includes("Promise.all(coverLoads)"));
assert.ok(source.includes('t("Sort")'));
console.log("Notible Library self-check passed.");
